# docker-compose.yml
version: '3.1'

services:

  shippy-cli-consignment:
    build: ./consignment-cli
    depends_on:
      - shippy-service-consignment
      - shippy-service-vessel

  shippy-service-consignment:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "datastore:27017"
    depends_on:
      - datastore

  shippy-service-vessel:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "datastore:27017"
    depends_on:
      - datastore

  datastore:
    image: mongo
    ports:
      - 27017:27017
